spring:
  profiles:
    # Active environment: dev, ft-a
    active: ft-a
  main:
    web-application-type: none

server:
  # Application context path
  context-path: /fusedemo
  port: 8080
  # lets listen on all ports to ensure we can be invoked from the pod IP
  address: 0.0.0.0

management:
  address: 0.0.0.0
  # Binding health checks to a different port
  port: 8088
  
camel:
  component:
    # Request and response schemas validation
    json-validator:
      enabled: true
  springboot:
    # Options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
    name: Camel
    main-run-controller: true

# Disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

logging:
  config: classpath:logback.xml