system:
  app-proxy:
    hostname: 10.211.100.102 #app-proxy.pccw.com
    port: 8080
    scheme: http
  ssl:
    keystore-path: classpath:tls/mule_xyz_pkcs12.pks.jks
    keystore-pass: hktruby
    truststore-path: classpath:tls/truststores.dev.p12
    truststore-pass: changeit
  redis:
    hostname: 127.0.0.1
    port: 6379
    password: null


on-prem:
  secret:
    itar-digispace: Shared_secret_sent_from_proxy_to_API_backend_dcb39ec39352d34b
  api:
    itar-digispace: itar-sit-a.hkt.com/api/assets/digiSpace
  file:
    large-file: examples/large-json-content-example-response.json

mule:
  api:
    # MuleSoft Mock Customer Rest API
    mock-customers: anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/c484da51-46e6-4745-8e69-ff960eff55a2/sample-customer-process-api/1.0.0/m/customers/
    # MuleSoft File Streaming API
    file-stream: hkt-file-transfer-test-20201029.jp-e1.cloudhub.io/
    salesforce-object: hktmule.prototyped.xyz/demo-sfdc-big-payload-ms-api-v1-fst-a/opportunities?record_count=47500
    test-vpc: hktmule.prototyped.xyz/test-vpc-8091-kaxnn/test-vpc
    customer-info: hktmule.prototyped.xyz/fst/a/com/customer-info/proc/api/v1/customer-info
    salesforce-contacts: hktmule.prototyped.xyz/test-salesforce-contacts-ms-api-v1-fst-a/contacts
  proxy: hktmule.prototyped.xyz

kafka:
  bridge:
    base-url: my-bridge-bridge-service-ruby-dev.apps.openshift3.com
    subscribe-timeout: 3000
    subscribe-maxBytes: 1024
  bootstrap:
    hostname: my-bridge-bridge-service-ruby-dev.apps.openshift3.com
    port: 443
    truststore-path: classpath:tls/msghub-ft-a.truststore.jks
    truststore-pass: password
    protocol: SSL
  gateway:
    hostname: msghub-bridge-ft-a.hkt.com #p2.uamp.hkt.com
    apikey: 89c580cd88505a4940e30d4ea495c7d8
  topic:
    name: ruby-topic
    partition: 0
    consumer-group: my-topic-consumer-group
    consumer-name: my-topic-consumer
