system:
  # HKT app proxy for internal application call external APIs
  app-proxy:
    hostname: app-proxy.pccw.com
    port: 8080
    # proxy scheme type
    scheme: http
  ssl:
    truststore-path: classpath:tls/truststores.ft-a.p12
    truststore-pass: changeit

on-prem:
  api:
    itar-digispace: itar-sit-a.hkt.com/api/assets/digiSpace

mule:
  api:
    # MuleSoft Mock Customer Rest API
    mock-customers: anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/c484da51-46e6-4745-8e69-ff960eff55a2/sample-customer-process-api/1.0.0/m/customers/
    # MuleSoft File Streaming API
    file-stream: hkt-file-transfer-test-20201029.jp-e1.cloudhub.io/
    test-vpc: np1.muleamp.hkt.com/test-vpc-8091-kaxnn/test-vpc
    customer-info: np1.muleamp.hkt.com/fst/a/com/customer-info/proc/api/v1/customer-info
    salesforce-contacts: np1.muleamp.hkt.com/test-salesforce-contacts-ms-api-v1-fst-a/contacts
  proxy: np1.muleamp.hkt.com

kafka:
  bridge:
    base-url: msghub-bridge-ft-a.hkt.com
    subscribe-timeout: 3000
    subscribe-maxBytes: 1024
  bootstrap:
    hostname: 10.168.104.4 #msghub-ft-a.hkt.com
    port: 443
    truststore-path: classpath:tls/msghub-ft-a.truststore.jks
    truststore-pass: password
    protocol: SSL
  gateway:
    hostname: msghub-bridge-ft-a.hkt.com #p2.uamp.hkt.com
    apikey: 89c580cd88505a4940e30d4ea495c7d8
  topic:
    name: ruby-topic
    partition: 0
    consumer-group: ruby-group
    consumer-name: ruby-consumer
