server:
  port: 8080
  # lets listen on all ports to ensure we can be invoked from the pod IP
  address: 0.0.0.0

management:
  address: 0.0.0.0
  # Binding health checks to a different port
  port: 8088
  
camel:
  component:
    # to vilidate request and response schemas
    json-validator:
      enabled: true

  springboot:
    # the options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
    name: FuseRest
    main-run-controller: true

spring:
  main:
    web-application-type: none

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

logging:
  config: classpath:logback.xml

appProxy:
  ip: 10.211.100.102
  port: 8080

mockapi:
  # MuleSoft Mock Customer Rest API
  customers-api: anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/c484da51-46e6-4745-8e69-ff960eff55a2/customer-api/1.0.5/m/customers/
mulesoft:
  # MuleSoft File Streaming API
  file-stream-api: hkt-file-transfer-test-20201029.jp-e1.cloudhub.io/
  test-vpc: np1.muleamp.hkt.com/test-vpc-8091-kaxnn/test-vpc