appProxy:
  host: 10.211.100.102 #app-proxy.pccw.com
  port: 8080

ssl:
  keystore:
    path: classpath:tls/truststores.uat.p12
    password: changeit

mock:
  api:
    # MuleSoft Mock Customer Rest API
    customers: anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/c484da51-46e6-4745-8e69-ff960eff55a2/sample-customer-process-api/1.0.0/m/customers/

mulesoft:
  api:
    # MuleSoft File Streaming API
    file-stream: hkt-file-transfer-test-20201029.jp-e1.cloudhub.io/
    test-vpc: np1.muleamp.hkt.com/test-vpc-8091-kaxnn/test-vpc
  proxy: np1.muleamp.hkt.com

kafka:
  bridge:
    baseurl: p.uamp.hkt.com/rubykafka
    consumer:
      groupid: my-topic-consumer-group
      name: my-topic-consumer
  subscribe:
    timeout: 3000
    maxBytes: 1024
    topics:
      topicname: ruby-topic
      partitionid: 0

  server:
    hostname: my-cluster-kafka-bootstrap-ruby-dev.apps.openshift3.com
    port: 443
  ssl:
    protocol: SSL

3scale:
  apikey: 89c580cd88505a4940e30d4ea495c7d8
  host: p2.uamp.hkt.com
