appProxy:
  ip: 10.211.100.102
  port: 8080

ssl:
  keystore:
    path: classpath:truststores.p12
    password: changeit

mockapi:
  # MuleSoft Mock Customer Rest API
  customers-api: anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/c484da51-46e6-4745-8e69-ff960eff55a2/sample-customer-process-api/1.0.0/m/customers/

mulesoft:
  # MuleSoft File Streaming API
  file-stream-api: hkt-file-transfer-test-20201029.jp-e1.cloudhub.io/
  test-vpc: np1.muleamp.hkt.com/test-vpc-8091-kaxnn/test-vpc

kafka:
  bridge:
    baseurl: p.uamp.hkt.com/rubykafka/topics/
    consumer:
      groupid: my-topic-consumer-group
      name: my-topic-consumer
    topics:
      topicname: ruby-topic
      partitionid: 0
  3scale:
    apikey: 89c580cd88505a4940e30d4ea495c7d8
  server:
    hostname: my-cluster-kafka-bootstrap-ruby-dev.apps.openshift3.com
    port: 443
  ssl:
    protocol: SSL
  groupId: my-topic-consumer-group


